name: deploy
on:
    - push
    - workflow_dispatch
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: get code
              uses: actions/checkout@v4
            - name: install node
              uses: actions/setup-node@v4
              with: 
                node-version: 20
            - name: node version
              run: node -v  
            - name: dependencies
              run: npm ci
            - name: run test
              run: npm run test